modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/raoulvdberge/refinedpipes"
[[mods]]
modId="refinedpipes"
version="${version}"
displayName="Refined Pipes"
authors="Refined Pipes authors"
description='''
Pipes that are refined. What more do you want?
'''
