modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/raoulvdberge/refinedpipes"
[[mods]]
modId="refinedpipes"
version="${version}"
displayName="Refined Pipes"
authors="Refined Pipes authors"
description='''
Refined Pipes is a Minecraft mod that adds pipes.
'''
