modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/refinedmods/refinedpipes"
[[mods]]
modId="refinedpipes"
version="${version}"
displayName="Refined Pipes"
authors="Refined Mods"
description='''
Refined Pipes is a Minecraft mod that adds pipes.
'''
